package dev.gaferneira.notificapp.core.ui.theme

import androidx.compose.ui.graphics.Color

// Deep Tech Precision — Dark
val DeepTechPrimaryDark = Color(0xFF6366F1)
val DeepTechOnPrimaryDark = Color(0xFFFFFFFF)
val DeepTechPrimaryContainerDark = Color(0xFF32309E)
val DeepTechOnPrimaryContainerDark = Color(0xFFE0E0FF)
val DeepTechSecondaryDark = Color(0xFF14B8A6)
val DeepTechOnSecondaryDark = Color(0xFF00201C)
val DeepTechSecondaryContainerDark = Color(0xFF0E6E63)
val DeepTechOnSecondaryContainerDark = Color(0xFFC7FFF4)
val DeepTechTertiaryDark = Color(0xFFF59E0B)
val DeepTechOnTertiaryDark = Color(0xFF241A00)
val DeepTechTertiaryContainerDark = Color(0xFF8A5C00)
val DeepTechOnTertiaryContainerDark = Color(0xFFFFE8BF)
val DeepTechBackgroundDark = Color(0xFF121212)
val DeepTechOnBackgroundDark = Color(0xFFE6E6E6)
val DeepTechSurfaceDark = Color(0xFF121212)
val DeepTechOnSurfaceDark = Color(0xFFE6E6E6)
val DeepTechSurfaceVariantDark = Color(0xFF262626)
val DeepTechOnSurfaceVariantDark = Color(0xFFB0B0B0)
val DeepTechOutlineDark = Color(0xFF4D4D4D)

// Deep Tech Precision — Light
val DeepTechPrimaryLight = Color(0xFF4F46E5)
val DeepTechOnPrimaryLight = Color(0xFFFFFFFF)
val DeepTechPrimaryContainerLight = Color(0xFFE2E0FF)
val DeepTechOnPrimaryContainerLight = Color(0xFF16137A)
val DeepTechSecondaryLight = Color(0xFF0D9488)
val DeepTechOnSecondaryLight = Color(0xFFFFFFFF)
val DeepTechSecondaryContainerLight = Color(0xFFCCF5EE)
val DeepTechOnSecondaryContainerLight = Color(0xFF00352E)
val DeepTechTertiaryLight = Color(0xFFA54100)
val DeepTechOnTertiaryLight = Color(0xFFFFFFFF)
val DeepTechTertiaryContainerLight = Color(0xFFFFDBC6)
val DeepTechOnTertiaryContainerLight = Color(0xFF381400)
val DeepTechBackgroundLight = Color(0xFFFAFAFC)
val DeepTechOnBackgroundLight = Color(0xFF1A1B1E)
val DeepTechSurfaceLight = Color(0xFFFAFAFC)
val DeepTechOnSurfaceLight = Color(0xFF1A1B1E)
val DeepTechSurfaceVariantLight = Color(0xFFE7E7EC)
val DeepTechOnSurfaceVariantLight = Color(0xFF64748B)
val DeepTechOutlineLight = Color(0xFFC1C4CE)
